#!/usr/bin/env bash
#Configuring a remote host to accept connections without password
Include /etc/ssh/ssh_config.d/*.conf
Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
