#!/usr/bin/env bash
# Update package lists
apt-get update -y
apt-get install nginx -y

# Create custom HTML page with required string
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx restart
netstat -lnt | grep ':80 '
